### ISSUE TITLE
Regression of generating incorrect output by bf2jit

### ISSUE THREAD

**Issue by jserv** [rdebath/Brainfuck#1]
While executing `bf2jit` on x86_64/Linux, I found a regression of [bfcl](https://github.com/rmmh/beefit/blob/master/test/bfcl.bf) (a BrainFuck compiler for Linux written itself in BrainFuck). The way to reproduce:

``` shell
bf2any/bf2jit test/bfcl.bf < test/fizzbuzz.bf > out
chmod +x out
./out
Segmentation fault
```

The file `test/fizzbuzz.bf` was taken from [fizzbuzz.bf](https://github.com/rmmh/beefit/blob/master/test/fizzbuzz.bf). Instead, if I use [beefit](https://github.com/rmmh/beefit), the generated file is capable to execute without problems.

**Comment by rdebath** [comment]
Looks like this isn't my bug.
By default bf2jit and several of the other interpreters and compilers use 32bit or large cells. If you give bf2jit the "-b" argument it generates code with 8bit cells. With this configuration the  executable generated by bfcl works correctly.

Note: for tritium the '-B' for binary I/O is needed too.

**Comment by jserv** [comment]
@rdebath: Thanks for your explanation. It works quite well with argument `-b` appended.
