### ISSUE TITLE
calculating sums in brainfuck

### ISSUE THREAD

**Issue by clarkzjw** [rdebath/Brainfuck#3]
Hi, there.

Do you have any ideas about calculating the sums of numbers implemented in brainfuck? 

For example, calculating the sums from 1 to a billion?

Thank you.

**Comment by rdebath** [comment]
The [Esolangs Wiki](https://esolangs.org/) has a page full of different [algorithms](https://esolangs.org/wiki/Brainfuck_algorithms) for code fragments that are simple in other languages but a bit complex when translated to brainfuck.

Of course there is the problem on how you represent numbers larger than 255. The simplest is to say that the interpreter must have a larger cell size, the [bitwidth conversions](https://esolangs.org/wiki/Brainfuck_bitwidth_conversions) can fix smaller interpreters.

Another, that allows unlimited values, is a ["Bijective"](https://en.wikipedia.org/wiki/Bijective_numeration) system.

BTW: By "sums" do you mean the [Triangle numbers](https://en.wikipedia.org/wiki/Triangular_number) ?

**Comment by clarkzjw** [comment]
It seems quite complex in brainfuck.

For "sums", yes, it is actually Triangle numbers. 

I am collecting implementations on calculating sums in different programming languages. Just for fun actually. I have some of them so far. See [here](https://github.com/JinweiClarkChao/one-two-three...infinity). And I came across an idea today that whether brainfuck can do that. So I came here to open this issue. After reading the links above, it seems rather difficult.

**Comment by rdebath** [comment]
I suspect the most time consuming thing to do will be the divide by 10 that would be needed to print out an 18 digit number. But if the numbers are held in base 10 the printout would be trivial. The you'd "just" need to write base 10 addition and subtraction routines for 20 digit numbers... that should be feasible, if a little slow.

**Comment by clarkzjw** [comment]
Well, I still cannot figure out the solution yet. Close this issue for now.
