### ISSUE TITLE
How do you handle OptimTease loop unrolling ?

### ISSUE THREAD

**Issue by ExtReMLapin** [rdebath/Brainfuck#8]
So on [my brainfuck to luajit transpiler](https://github.com/ExtReMLapin/fast_brainfuck.lua) i cannot get [OptimTease](https://github.com/rdebath/Brainfuck/blob/master/testing/OptimTease.b) to work because of the number of loops, i get a syntax level error.
I [described here the others optimizations I do](https://github.com/JakuJ/BFC-10000/issues/1) but I cannot manage to get my head round about optimtease.

If you can read Lua, here is the reformated code I produce.
[out.zip](https://github.com/rdebath/Brainfuck/files/6241787/out.zip)

**Comment by ExtReMLapin** [comment]
Also here is my IR  : 


```Lua

local INC = 1
local MOVE = 2
local PRINT = 3
local LOOPSTART = 4
local LOOPEND = 5
local READ = 6
local ASSIGNATION = 7
local MEMSET = 8
local UNROLLED_ASSIGNATION = 9
local IFSTART = 10
local IFEND = 11
local FUNC_CALL = 12
local PRINT_REPEAT = 13

local instructions = {
    ["+"] = INC,
    ["-"] = INC,
    [">"] = MOVE,
    ["<"] = MOVE,
    ["["] = LOOPSTART,
    ["]"] = LOOPEND,
    ["."] = PRINT,
    [","] = READ
}

local IRToCode = {
    [INC] = "data[i]=data[i]+%i ",
    [MOVE] = "i=i+%i ",
    [LOOPSTART] = "while data[i]~=0 do ",
    [LOOPEND] = "end ",
    [PRINT] = "w(data[i])",
    [READ] = "data[i]=r()",
    [ASSIGNATION] = "data[i]=%i ",
    [MEMSET] = "ffi.fill(data+i+%i, %i, %i)",
    [UNROLLED_ASSIGNATION] = "data[i+%i] = data[i+%i] + (-(data[i]/%i))*%i ",
    [IFSTART] = "if (data[i] ~= 0) then ",
    [IFEND] = "end ",
    [FUNC_CALL] = "%s() ",
    [PRINT_REPEAT] = "w2(data[i], %i)"
}
```

**Comment by rdebath** [comment]
By creating over 2500 functions.

A lua while loop gets converted into jumps during it's "compile", these jumps have a limited range (65535 p-code instructions IIRC) so when I find a while loop that has more than a few instructions in it I create a function for the contents of the loop and put the while loop around the function call. A simple example is in my [bf2lua.lua](https://github.com/rdebath/Brainfuck/blob/master/extras/bf2lua.lua)

To avoid problems with more complex conversions I only allow 4096 of my tokens inside a loop, the 16:1 ratio seems to be sufficient. As it happens this is also sufficient to avoid the problem that's hit you first with too many nested while loops.

Other languages that have similar issues are Java, Julia, Free Pascal and some versions of Python.

C almost has the issue too, in that trying to optimise a huge function with a heavily optimising compiler (eg: GNU-C, Clang) takes a very long time and huge amounts of memory for little gain. OTOH splitting the code into smaller (static) functions compiles a lot faster and the compiler notices that many of these functions are identical and so only one copy is generated.

**Comment by ExtReMLapin** [comment]
Well actually the issue wasn't caused by the [size of D register (16 bits)](http://wiki.luajit.org/Bytecode-2.0), it's caused by the manually hardcoded syntax level.
I already solved the JMP operand max  size by splitting it into multiple function as you describe it (with min and max size). I met this problem with `LostKingdom.b`


The 2^16-1 limit only appears on LuaJIT tho, not LuaPUC.

>To avoid problems with more complex conversions I only allow 4096 of my tokens inside a loop

On the Lua version ? I managed to get the exact max number of allowed IR instructions by hardcoding the "weight" or each IR instructions into my transpiller.

**Comment by rdebath** [comment]
Right, so you _had_ already spotted that.
Well, as I said, the solution to "too many nested whiles" is the same.
You have to split the functions up some more. 

I just made the functions "smaller" by the measure I was already counting for lua as it would still keep the hottest loops in single functions.

OTOH the trivial interpreter below was counting the exact depth of the nesting, and Optimtease goes to about 260, so I had to increase the `jmpstk` to 999. Unfortunately, the lua limit does indeed seem to be hard coded. 

To match your very nice instruction counting you'd have to count the exact number of "nested control statements and binary operations" and generate a new function when this gets too deep for `LUAI_MAXCCALLS`. As far as I can see that is the only way to stop lua's recursive decent parser using up more of the OS stack (which it treats as a scarce resource).

PS: I've done a bit of fixing on my bf2lua.c and a better count of the number of needed functions is 21. 

``` c
void minibf(char * b)
{
    char *p, *jmpstk[256];
    int c, i=0, sp = 0;
    unsigned short m=0;

    for(p=b;*p;p++)switch(*p) {
        case '>': m++;break;
        case '<': m--;break;
        case '+': t[m]++;break;
        case '-': t[m]--;break;
        case '.': putch(t[m]);break;
        case ',': if((c=getchar())!=EOF)t[m]=c;break;
        case '[': if(t[m]==0) while((i+=(*p=='[')-(*p==']'))&&p[1]) p++;
                  else jmpstk[sp++] = p;
                  break;
        case ']': if(sp) { if(t[m]!=0) p=jmpstk[sp-1]; else sp--;} break;
    }
}
```
